### ISSUE TITLE
The border-transition of the search field is overwritten.

### ISSUE THREAD

**Issue by timlg07** [Nimplex/Minimal-StartPage#1]
The search input field (`#main .searchbar input`) has two transitions, with one overwriting the other:

![image](https://user-images.githubusercontent.com/33633786/104451341-b3d35800-55a1-11eb-9540-ff07cc6b87df.png)

**Expected behavior:**
The border transition should be enabled.

**Comment by Nimplex** [comment]
Repaired in latest commit [Link](https://github.com/Nimplex/Minimal-StartPage/commit/1d5874c55433bfdb182b6bbdcff702b667763ad8)
