### ISSUE TITLE
Chrome: Failed to load extension - Quick edit to manifest.json in the folder

### ISSUE THREAD

**Issue by gholtfrerich** [Nimplex/Minimal-StartPage#6]
When dragging into Chrome I would get the following:

**Failed to load extension
File
~\Downloads\Minimal-StartPage-main
Error
Could not load icon _'favicon.png'_ specified in 'icons'.
Could not load manifest.**

FIX: 
1. Opened _manifest.json_ in Notepad on Windows 10
2. In the code, changed both _"favicon.png"_  to  _"favicon.ico"_ and saved file
3. Verified that File Explorer still showed _manifest.json_ as a JSON File
4. Dragged _Minimal-StartPage-main_ folder into Chrome Extensions window

**Comment by timlg07** [comment]
I fixed this in #7, thanks for letting us know :)
